import Banner from "@/components/Banner";
import Fruitjuice from "@/components/Fruitjuice";
import Menu from "@/components/Menu";
import Navbar from "@/components/Navbar";
import Newarrivels from "@/components/Newarrivels";
import Poster from "@/components/Poster";
import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Menu />
      <Poster />
      <Newarrivels />
      <Banner />
      <Fruitjuice />
    </div>
  );
}
